### PR TITLE
Admin UI Changes

### PR DESCRIPTION
**Pull request by Beytoven**
I've updated the Admin UI to look better, adding controls around editing and saving the range and score information. Feel free to checkout the branch and make more changes as I'm off to get married 😎

### CODE REVIEW

**Comment by rickposp** [comment]
I see some commented code that should be removed.

**Comment by rickposp** [comment]
I also don't see any input validation for the scoring range fields. We should at least check that the input is an integer.

**Comment by pavan149679** [comment]
Hey @rickposp I have removed the commented code and also added more validations around the ranges and scores before making the post call. Added alerts in place for better display. Feel free to review this and let me know if you think we need more changes.

**Comment by rickposp** [comment]
I still see a lot of commented HTTML in UI/src/app/dashboard/views/admin.html that should be removed. We also need to check that the inputs are integers, you failed the cat test again. I would also adjust the css of the page so that the main pane fills the screen.

**Pull request merged**
